spring:
  datasource:
    url: jdbc:postgresql://monorail.proxy.rlwy.net:10985/railway
    username: postgres
    password: pdOHBiDHGazfJjOeYjyPjenHIAFNniNj
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate